# Set environment to use linux OS
os: linux

# Set environment to use PHP
language: php

# Check the master branch only
branches:
  only:
    - master
    
# Send notifications (via email) when build fails
notifications:
  email:
    on_success: never
    on_failure: always

# Versions of PHP to test plugin against
php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'
    - '8.0'

# PHP files to check for syntax errors
script:
  - php -l plugin.php
  - php -l includes/settings-page/admin-menu.php
  - php -l includes/settings-page/settings-callbacks.php
  - php -l includes/settings-page/settings-page.php
  - php -l includes/settings-page/settings-register.php
  - php -l includes/settings-page/settings-validate.php
  - php -l tribe/events/month/calendar-body/day/calendar-events/calendar-event/tooltip/title.php