# Don't give sudo level access
sudo: false

# Set environment to use PHP
language: php

# Check the master branch only
branches:
  only:
    - master
    
# Send notifications (via email) when build fails
notifications:
  email:
    on_success: never
    on_failure: always

# Versions of PHP to test plugin against
php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'

# PHP files to check for syntax errors
script:
  - phpunit --syntax-check plugin.php
  - phpunit --syntax-check includes/settings-page/admin-menu.php
  - phpunit --syntax-check includes/settings-page/settings-callbacks.php
  - phpunit --syntax-check includes/settings-page/settings-page.php
  - phpunit --syntax-check includes/settings-page/settings-register.php
  - phpunit --syntax-check includes/settings-page/settings-validate.php
  - phpunit --syntax-check tribe-events/month/tooltip.php
