name: "WordPress Plugin Check"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          coverage: none
          tools: wp-cli, composer:v2.9.8
      - name: Install dist-archive-command
        env:
          GITHUB_TOKEN: ""
          GH_TOKEN: ""
          COMPOSER_AUTH: ""
        run: wp package install wp-cli/dist-archive-command:v3.1.0
      - name: Build plugin
        run: |
          wp dist-archive . ./display-event-locations-tec.zip
          mkdir tmp-build
          unzip display-event-locations-tec.zip -d tmp-build
      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: "./tmp-build/display-event-locations-tec"
