name: 'WordPress Plugin Check'

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: latest
        coverage: none
        tools: wp-cli
    - name: Install latest version of dist-archive-command
      # Pinned to v3.1.0 because v3.2.0+ requires wp-cli ^2.13, which hasn't been released yet.
      # Revisit when wp-cli >2.12.0 is available: https://github.com/wp-cli/wp-cli/releases
      run: wp package install wp-cli/dist-archive-command:@v3.1.0
    - name: Build plugin
      run: |
        wp dist-archive . ./display-event-locations-tec.zip
        mkdir tmp-build
        unzip display-event-locations-tec.zip -d tmp-build
    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1
      with:
        build-dir: './tmp-build/display-event-locations-tec'