name: 'WordPress Plugin Check'

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1
      with:
        # List of directories to exclude from checks.
        # Each directory should be separated with new lines.
        #
        # Default: ''
        exclude-directories: './.github'
